better if statement for packer dne

diff --git a/vagrant/ubuntu-dev/Vagrantfile b/vagrant/ubuntu-dev/Vagrantfile
--- a/vagrant/ubuntu-dev/Vagrantfile
+++ b/vagrant/ubuntu-dev/Vagrantfile
@@ -55,7 +55,8 @@ Vagrant.configure("2") do |config|
 
     # packer setup, from source
     which packer
-    if [ "$?" -eq "1" ]; then # if exit code is nonzero, it is not a command  
+    if [ ! "$?" -eq "0" ]; then # if exit code is nonzero, it is not a command  
+      echo "Installing packer from source, as it does not exist on path!"
       pushd /tmp/
       mkdir -p /tmp/packer-setup/
       pushd /tmp/packer-setup/
